/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model


case class AddEmbedding(
  embeddings: Option[Seq[org.json4s.JValue]] = None,
  metadatas: Option[Seq[AddEmbeddingMetadatasInner]] = None,
  documents: Option[Seq[AddEmbeddingDocumentsInner]] = None,
  uris: Option[Seq[AddEmbeddingDocumentsInner]] = None,
  ids: Seq[String]
)

