/** FastAPI No description provided (generated by Openapi Generator
  * https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.1.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package org.openapitools.client.model

import com.fasterxml.jackson.annotation.*

case class CreateCollection(
    name: String,
    configuration: Option[Any] = None,
    metadata: Option[Any] = None,
    get_or_create: Option[Boolean] = None
)
