/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model



object IncludeEnum extends Enumeration {
    type IncludeEnum = IncludeEnum.Value
    val Documents = Value("documents")
    val Embeddings = Value("embeddings")
    val Metadatas = Value("metadatas")
    val Distances = Value("distances")
    val Uris = Value("uris")
    val Data = Value("data")
}
